### ISSUE TITLE
What is the full set of steps to set up the API on a fresh Ubuntu server?

### ISSUE THREAD

**Issue by aih** [aih/billtitleindex#5]
1. From beginning to end, what steps are needed to set up the scrapers and data? All of the steps of the README (https://github.com/aih/billtitleindex/blob/develop/billtitleindex/README.md), or only:

    a. populate the data (https://github.com/aih/billtitleindex/blob/develop/billtitleindex/README.md#how-to-update-recent-billstatus-xml-files) and then 
    b. `docker-compose up` with https://github.com/aih/billtitleindex/blob/develop/billtitleindex/docker-compose.yml
    
2. Once deployed with `docker-compose up`, what steps does the system take? Does it scrape, process and make the data available on the API? How often?

**Comment by ninjaguru-git** [comment]
1. As you can see in README.md, each step is available for setup each component individually on local development environment.
The last step using `docker-compose` is a production-ready solution. So all components setup and configuration are in `docker-compose.yml` file.
2. [scraping-task-midnight-daily](https://github.com/aih/billtitleindex/blob/develop/billtitleindex/billtitleindex/celery.py#L17) is responsible for scraping bills.
[pipeline-task-everyday-4am](https://github.com/aih/billtitleindex/blob/develop/billtitleindex/billtitleindex/celery.py#L21) is used for running pipeline at 4:00 AM.
After deploying all with `docker-compose`, if you want do start scraping manually, you can call http://localhost:8080/scraping/ with GET request. And for start running pipeline manually, please call http://localhost:8080/pipeline/.
